ALTER TABLE jobs ADD COLUMN IF NOT EXISTS sku_id BIGINT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reason TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS priority INT NOT NULL DEFAULT 10;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS max_attempts INT NOT NULL DEFAULT 5;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS locked_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS available_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_jobs_reason') THEN
    ALTER TABLE jobs ADD CONSTRAINT chk_jobs_reason CHECK (reason IN ('manual','refill','api','admin'));
  END IF;
END $$;
